### ISSUE TITLE
Give jaraco access to publish to PyPI

### ISSUE THREAD

**Issue by jaraco** [brandon-rhodes/backports#8]
To add a collaborator in PyPI:

1. Log into PyPI.
2. Browse to the project (https://pypi.org/project/backports).
3. Click 
![Manage Project](https://user-images.githubusercontent.com/308610/144645493-6e14a031-ca4f-41f4-9d28-83272c47a268.png)
4. Select 
![Collaborators](https://user-images.githubusercontent.com/308610/144645559-cc279698-519c-465e-9f77-fb2184d400b7.png)
5. Add the collaborator's user name under User and select a role. Owners can administer other collaborators and perform other maintenance operations like yanking and deleting. Maintainers can upload new versions only. Click Invite.

My username in pypi is the same as here.

**Comment by jaraco** [comment]
I'd prefer to have ownership access in order to reduce the bus factor on the project. I promise to be respectful and to defer to the primary owner's wishes.

**Comment by brandon-rhodes** [comment]
Done!
